"use client";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { LogoIcon } from "@/components/logo";
import { ThemeToggle } from "@/components/theme-toggle";
import { adminFetch, logoutAdminSession } from "@/lib/admin-session";

const items = [["/admin", "仪表盘", "📊"], ["/admin/posts", "文章管理", "📝"], ["/admin/categories", "分类管理", "📁"], ["/admin/tags", "标签管理", "🏷️"], ["/admin/comments", "评论管理", "💬"], ["/admin/friends", "友链管理", "🔗"], ["/admin/settings", "站点设置", "⚙️"]] as const;
const titles: Record<string, string> = { "/admin": "仪表盘", "/admin/posts": "文章管理", "/admin/categories": "分类管理", "/admin/tags": "标签管理", "/admin/comments": "评论管理", "/admin/friends": "友链管理", "/admin/settings": "站点设置" };

export function AdminShell({ children }: { children: React.ReactNode }) {
  const pathname = usePathname() || "/"; const router = useRouter(); const [open, setOpen] = useState(false); const [ready, setReady] = useState(pathname === "/admin/login");
  useEffect(() => { if (pathname === "/admin/login") { setReady(true); return; } adminFetch("/api/admin/dashboard").then((response) => { if (!response.ok) router.replace("/admin/login"); else setReady(true); }).catch(() => router.replace("/admin/login")); }, [pathname, router]);
  if (pathname === "/admin/login") return <>{children}</>;
  const section = Object.keys(titles).filter((path) => path === "/admin" ? pathname === path : pathname.startsWith(path)).sort((a, b) => b.length - a.length)[0];
  if (!ready) return <div className="grid min-h-screen place-items-center bg-[var(--color-bg-secondary)] text-sm text-[var(--color-text-secondary)]">正在验证登录状态…</div>;
  return <div className="flex min-h-screen bg-[var(--color-bg-secondary)]"><aside className={`fixed left-0 top-0 z-40 flex h-screen w-72 flex-col border-r border-[var(--color-border)] bg-[var(--color-bg)] transition-transform lg:w-60 lg:translate-x-0 ${open ? "translate-x-0" : "-translate-x-full"}`}><div className="flex h-16 items-center gap-2 border-b border-[var(--color-border)] px-4"><Link href="/admin" className="flex items-center gap-2"><LogoIcon size={28} /><span className="rounded bg-[var(--color-primary-light)] px-1.5 py-0.5 text-xs font-medium text-[var(--color-primary)]">Admin</span></Link></div><nav className="flex-1 space-y-1 overflow-y-auto p-3">{items.map(([href, label, icon]) => { const active = href === "/admin" ? pathname === href : pathname.startsWith(href); return <Link key={href} href={href} onClick={() => setOpen(false)} className={`flex items-center gap-3 rounded-lg px-3 py-2 text-sm ${active ? "bg-[var(--color-primary-light)] font-medium text-[var(--color-primary)]" : "text-[var(--color-text-secondary)] hover:bg-[var(--color-bg-tertiary)]"}`}><span>{icon}</span>{label}</Link>; })}</nav><div className="border-t border-[var(--color-border)] p-3"><Link href="/" className="block rounded-lg px-3 py-2 text-sm text-[var(--color-text-secondary)]">← 返回前台</Link></div></aside>{open && <button type="button" onClick={() => setOpen(false)} className="fixed inset-0 z-30 bg-black/30 lg:hidden" aria-label="关闭管理菜单" />}<div className="flex min-w-0 flex-1 flex-col lg:ml-60"><header className="sticky top-0 z-30 flex h-16 items-center justify-between border-b border-[var(--color-border)] bg-[var(--color-bg)]/85 px-4 backdrop-blur lg:px-6"><div className="flex items-center gap-3"><button type="button" onClick={() => setOpen(true)} className="grid h-9 w-9 place-items-center rounded-lg border border-[var(--color-border)] lg:hidden" aria-label="打开管理菜单">☰</button><h1 className="text-lg font-semibold">{titles[section] || (pathname.includes("/new") ? "新建文章" : pathname.includes("/edit") ? "编辑文章" : "管理后台")}</h1></div><div className="flex items-center gap-3"><ThemeToggle /><span className="hidden text-sm text-[var(--color-text-secondary)] sm:inline">Admin</span><button type="button" onClick={async () => { await logoutAdminSession(); router.replace("/admin/login"); }} className="rounded-lg border border-[var(--color-border)] px-3 py-1.5 text-sm">退出</button></div></header><main className="flex-1 p-4 sm:p-6">{children}</main></div></div>;
}
