import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ShareButton, ViewCounter } from "@/components/article-enhancements";
import { Comments } from "@/components/comments";
import { fetchInternalApi } from "@/lib/cloudflare";
import type { ApiResponse, PostDetail } from "@/lib/types";
import { getPublicSettings } from "@/lib/site-settings";

export const dynamic = "force-dynamic";
async function getPost(slug: string) { const response = await fetchInternalApi(`/api/v1/posts/${encodeURIComponent(slug)}`); if (response.status === 404) return null; if (!response.ok) throw new Error(`文章读取失败：${response.status}`); return ((await response.json()) as ApiResponse<PostDetail>).data; }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const slug = (await params).slug; const post = await getPost(slug); if (!post) return { title: "文章不存在" }; return { title: post.title, description: post.excerpt || post.title, alternates: { canonical: `/blog/${post.slug}` }, openGraph: { type: "article", title: post.title, description: post.excerpt || post.title, publishedTime: post.published_at || post.created_at, images: post.cover_url ? [post.cover_url] : [] } }; }
export default async function ArticlePage({ params }: { params: Promise<{ slug: string }> }) {
  const slug = (await params).slug; const [post, settings] = await Promise.all([getPost(slug), getPublicSettings()]); if (!post) notFound(); const displayDate = post.published_at || post.created_at;
  return <><div className="mx-auto max-w-6xl px-4 py-12"><div className="flex gap-8"><article className="prose mx-auto min-w-0 max-w-3xl flex-1"><header className="mb-8"><Link href="/blog" className="mb-4 inline-block text-sm text-[var(--color-text-tertiary)]">← 返回列表</Link><h1 className="text-3xl font-bold">{post.title}</h1><div className="mt-3 flex flex-wrap items-center gap-3 text-sm text-[var(--color-text-secondary)]"><time>{new Date(displayDate).toLocaleDateString("zh-CN")}</time><span>·</span><span>{post.word_count || "—"} 字</span><span>·</span><span><ViewCounter slug={post.slug} initialViews={post.view_count} /> 次阅读</span></div><div className="mt-4 flex flex-wrap gap-2">{post.categories?.map((category) => <Link key={category.id} href={`/blog/category/${category.slug}`} className="rounded-full bg-[var(--color-bg-secondary)] px-3 py-1 text-xs">{category.name}</Link>)}{post.tags?.map((tag) => <Link key={tag.id} href={`/blog/tag/${tag.slug}`} className="rounded-full bg-[var(--color-bg-secondary)] px-3 py-1 text-xs">#{tag.name}</Link>)}</div></header>{post.cover_url && <img src={post.cover_url} alt={post.title} className="mb-8 aspect-video w-full rounded-xl object-cover" />}<div id="post-content" dangerouslySetInnerHTML={{ __html: post.content_html || post.content }} /><div className="mt-8 flex items-center gap-3 border-t border-[var(--color-border)] pt-6"><span className="text-sm text-[var(--color-text-secondary)]">分享：</span><ShareButton /><a href={`https://twitter.com/intent/tweet?url=${encodeURIComponent(`${process.env.NEXT_PUBLIC_SITE_URL || "https://nami-blog.codeelite.workers.dev"}/blog/${post.slug}`)}&text=${encodeURIComponent(post.title)}`} target="_blank" rel="noopener" className="rounded-lg border border-[var(--color-border)] px-3 py-1.5 text-sm">𝕏 Twitter</a></div></article></div>{(post.prev || post.next) && <nav className="mx-auto mt-8 grid max-w-3xl gap-4 sm:grid-cols-2">{post.prev ? <Link href={`/blog/${post.prev.slug}`} className="rounded-xl border border-[var(--color-border)] p-4"><small>← 上一篇</small><div>{post.prev.title}</div></Link> : <div />}{post.next && <Link href={`/blog/${post.next.slug}`} className="rounded-xl border border-[var(--color-border)] p-4 text-right"><small>下一篇 →</small><div>{post.next.title}</div></Link>}</nav>}</div>{settings.comment_enabled !== false && <Comments postId={post.id} />}</>;
}
