"use client";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { Logo } from "@/components/logo";
import { adminFetch, saveAdminSession } from "@/lib/admin-session";
import { readJson, type ApiErrorResult } from "@/lib/json";
export default function LoginPage() {
  const router = useRouter(); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  useEffect(() => { adminFetch("/api/admin/dashboard").then((response) => { if (response.ok) router.replace("/admin"); }).catch(() => {}); }, [router]);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setError(""); const data = new FormData(event.currentTarget); try { const response = await fetch("/api/v1/auth/login", { method: "POST", headers: { "Content-Type": "application/json" }, credentials: "include", body: JSON.stringify({ username: data.get("username"), password: data.get("password") }) }); const result = await readJson<{ data: { accessToken: string; refreshToken: string } } & ApiErrorResult>(response); if (!response.ok) throw new Error(result.error?.message || "登录失败"); saveAdminSession({ accessToken: result.data.accessToken, refreshToken: result.data.refreshToken }); router.replace("/admin"); } catch (reason) { setError(reason instanceof Error ? reason.message : "登录失败"); setLoading(false); } }
  return <div className="flex min-h-screen items-center justify-center bg-[var(--color-bg-secondary)] px-4"><div className="w-full max-w-sm"><div className="mb-8 flex flex-col items-center"><Logo size="lg" /><p className="mt-2 text-sm text-[var(--color-text-secondary)]">管理后台登录</p></div><form onSubmit={submit} className="rounded-2xl border border-[var(--color-border)] bg-[var(--color-bg)] p-6 shadow-sm"><div className="space-y-4"><label className="block text-sm font-medium">用户名<input name="username" defaultValue="admin" required autoComplete="username" className="mt-1 block w-full rounded-lg border border-[var(--color-border)] px-3 py-2" /></label><label className="block text-sm font-medium">密码<input name="password" type="password" required autoComplete="current-password" className="mt-1 block w-full rounded-lg border border-[var(--color-border)] px-3 py-2" /></label>{error && <p className="rounded-lg bg-red-50 p-3 text-sm text-red-600">{error}</p>}<button disabled={loading} className="w-full rounded-lg bg-[var(--color-primary)] px-4 py-2 text-sm font-medium text-white disabled:opacity-50">{loading ? "登录中…" : "登录"}</button></div></form><p className="mt-4 text-center text-xs text-[var(--color-text-tertiary)]">本地首次登录密码请查看根目录 .env</p></div></div>;
}
